/*
 * JSP generated by Resin Professional 4.0.13 (built Tue, 09 Nov 2010 03:50:16 PST)
 */

package _jsp._web_22dinf._jsp._bossjob;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;

public class _index__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html");
    response.setCharacterEncoding("utf-8");
    String _caucho_request_character_encoding = request.getCharacterEncoding();
    if (_caucho_request_character_encoding == null || "".equals(_caucho_request_character_encoding))
      request.setCharacterEncoding("utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((basePath));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string4, 0, _jsp_string4.length);
    _caucho_expr_2.print(out, _jsp_env, false);
    out.write(_jsp_string5, 0, _jsp_string5.length);
    _caucho_expr_3.print(out, _jsp_env, false);
    out.write(_jsp_string6, 0, _jsp_string6.length);
    _caucho_expr_4.print(out, _jsp_env, false);
    out.write(_jsp_string7, 0, _jsp_string7.length);
    _caucho_expr_5.print(out, _jsp_env, false);
    out.write(_jsp_string8, 0, _jsp_string8.length);
    _caucho_expr_6.print(out, _jsp_env, false);
    out.write(_jsp_string9, 0, _jsp_string9.length);
    _caucho_expr_7.print(out, _jsp_env, false);
    out.write(_jsp_string10, 0, _jsp_string10.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 72739197937975180L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/jsp/bossjob/index.jsp"), 1008839200777890061L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${loginVO.account }");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${loginVO.password }");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${loginVO.url}");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${loginVO.captcha }");
      _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${loginVO.randomKey }");
      _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${loginVO.respCookies }");
      _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${errMsg }");
      _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${resume.baseName }");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;

  private final static char []_jsp_string10;
  private final static char []_jsp_string9;
  private final static char []_jsp_string5;
  private final static char []_jsp_string3;
  private final static char []_jsp_string6;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string8;
  private final static char []_jsp_string2;
  private final static char []_jsp_string7;
  private final static char []_jsp_string0;
  static {
    _jsp_string10 = "\"></div>\r\n	  		</div>\r\n  		</div>\r\n  		\r\n		\r\n  </body>\r\n\r\n\r\n<script>\r\n	function changeImg() {\r\n	debugger;\r\n		var imgSrc = $(\"#imgObj\");\r\n		var src = imgSrc.attr(\"src\");\r\n		imgSrc.attr(\"src\", chgUrl(src));\r\n		// \u65f6\u95f4\u6233\r\n		// \u4e3a\u4e86\u4f7f\u6bcf\u6b21\u751f\u6210\u56fe\u7247\u4e0d\u4e00\u81f4\uff0c\u5373\u4e0d\u8ba9\u6d4f\u89c8\u5668\u8bfb\u7f13\u5b58\uff0c\u6240\u4ee5\u9700\u8981\u52a0\u4e0a\u65f6\u95f4\u6233\r\n		function chgUrl(url) {\r\n			var timestamp = (new Date()).valueOf();\r\n			urlurl = url.substring(0, 17);\r\n			if ((url.indexOf(\"?\") >= 0)) {\r\n				urlurl = url + \"&t=\" + timestamp;\r\n			} else {\r\n				urlurl = url + \"?t=\" + timestamp;\r\n			}\r\n			return urlurl;\r\n		}\r\n	}\r\n</script>\r\n</html>\r\n".toCharArray();
    _jsp_string9 = "</div>\r\n			<div class = \"btn\"><input  type=\"submit\" value=\"\u767b\u5f55\"></div>\r\n			<div><a href=\"/bossjob/resume/index\"><input  type=\"button\" value=\"\u91cd\u65b0\u8bf7\u6c42\u63a5\u53e3\"></a></div>\r\n			</form>\r\n			\r\n	  		<div class=\"resupse\">\r\n				<h1>\u8fd4\u56de\u5185\u5bb9</h1>\r\n	  			<div>\u59d3\u540d\uff1a<input type=\"text\" value=\"".toCharArray();
    _jsp_string5 = "\" onclick=\"javaScript:changeImg()\"></div>\r\n			<div>\r\n				\u9a8c\u8bc1\u7801\uff1a<input type=\"text\" name=\"captcha\" value=\"".toCharArray();
    _jsp_string3 = "\"></div>\r\n			<div>\u5bc6\u7801\uff1a<input type=\"text\" name=\"password\" value=\"".toCharArray();
    _jsp_string6 = "\"> \r\n			</div>\r\n			 <input type=\"hidden\" name=\"randomKey\" value=\"".toCharArray();
    _jsp_string1 = "\r\n\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n<html>\r\n  <head>\r\n    <base href=\"".toCharArray();
    _jsp_string4 = "\"></div>\r\n			<div><img id=\"imgObj\" src=\"".toCharArray();
    _jsp_string8 = "\">\r\n			<div class=\"errMsg\">".toCharArray();
    _jsp_string2 = "\">\r\n    \r\n    <title>Boos\u76f4\u8058</title>\r\n    \r\n	<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n	<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n	<meta http-equiv=\"expires\" content=\"0\">    \r\n	<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n	<meta http-equiv=\"description\" content=\"This is my page\">\r\n	\r\n	  <script type=\"text/javascript\" src=\"js/jquery.js\"></script>  \r\n\r\n	<style type=\"text/css\">\r\n		.main{\r\n			margin: 10px; auto;\r\n		 	text-align: center;\r\n		}\r\n		.main div{\r\n			padding: 5px\r\n		}\r\n		.main h1{\r\n		 	font-size: 16px;\r\n		}\r\n		.resupse{\r\n			margin-top: 20px;\r\n		}\r\n		.errMsg{\r\n			color: red;\r\n		}\r\n		.imgClass,.captcha{\r\n		 float: left;\r\n		}\r\n	</style>\r\n\r\n  </head>\r\n  \r\n  <body>\r\n  		<div class=\"main\">\r\n  			<h1>Boos\u76f4\u8058</h1>\r\n  			<form action=\"/bossjob/resume/get\">\r\n			<div>\u5e10\u53f7\uff1a<input type=\"text\" name=\"account\" value=\"".toCharArray();
    _jsp_string7 = "\">\r\n   			 <input type=\"hidden\" name=\"respCookies\" value=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n".toCharArray();
  }
}
